### ISSUE TITLE
Update for nginx 1.18 (Focal)

### ISSUE THREAD

**Issue by shaneshort** [phusion/nginx-modsecurity-ubuntu#1]
Hi Guys,

Now 20.04 is the latest ubuntu LTS, it would be nice if the PPA was updated to support it. I gave it a go myself manually but had a few dramas. If I can help in any way, let me know!

**Comment by stuntsman** [comment]
+1

**Comment by cilex-ft** [comment]
+1 @FooBarWidget please refresh the ppa! That's so badly needed...

**Comment by FooBarWidget** [comment]
There's a 20.04 package now.
